### ISSUE TITLE
Why min sdk is 16?

### ISSUE THREAD

**Issue by ankit662002** [mcatta/android-instagram-connector#2]
Hi
May I ask why the min sdk is 16?
Any chance that you can lower it to 14?
I downloaded the code and imported on Studio and tried to change minsdk and it didnt show any error.
Can you please change the min sdk to 14?

**Comment by mcatta** [comment]
Hi,
sorry for lateness, i was i vacation last weeks, changed min sdk to 14.

**Comment by ankit662002** [comment]
Thanks
