### ISSUE TITLE
How to log out the current user?

### ISSUE THREAD

**Issue by vishnuharidas** [mcatta/android-instagram-connector#3]
How to log out the current user? Couldn't find a way to do so.

Something like `InstagramSession.logOut()`

**Comment by mcatta** [comment]
You should destroy the shared preference key with token and invalidate sessions. I will add it this weekend.

thank you for you help

**Comment by mcatta** [comment]
I have added the logout method on version 1.3.2 https://github.com/mcatta/android-instagram-connector/releases/tag/v1.3.2
