### ISSUE TITLE
Dialog dismiss callback?

### ISSUE THREAD

**Issue by aFrag** [mcatta/android-instagram-connector#4]
Hi, is there a callback if the user doesn't login and dismiss the dialog?

**Comment by vishnuharidas** [comment]
Currently no callback is there. But I have added and submitted a PR.

Here are the changes if you are working on the source code directly in your project: https://github.com/mcatta/android-instagram-connector/pull/5/commits/4a3a5192769c055ee7048a67790172e0faee504d

**Comment by mcatta** [comment]
Thank you @vishnuharidas i have merged you commit
